apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dgcg23cme-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dgcg23cme-nodejs 
  name: dgcg23cme-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dgcg23cme-nodejs 
